export type ProfileStates = "Offline"
  | "In Lobby"
  | "Champion Selection"
  | "In Match"
  | "Online"
  | "Unknown"

export type Portals = "Unknown"
  | "PC"
  | "Steam"
  | "Epic"
  | "PSN"
  | "XboxLive"
  | "Nintendo"
  | "Discord"
  | "Mixer"
  | "Facebook"
  | "Google"

export type Queue = "Casual_Siege"
  | "Team Deathmatch"
  | "Onslaught"
  | "Ranked Keyboard"
  | "Ranked Controller"
  | "Training Siege"
  | "Training Team Deathmatch"
  | "Training Onslaught"
  | "Test_Maps"


export type ChampionRole = "Damage"
  | "Flank"
  | "Support"
  | "Tank"

export type Champions = "Androxus"
  | "Ash"
  | "Atlas"
  | "Barik"
  | "BombKing"
  | "Buck"
  | "Cassie"
  | "Corvus"
  | "Dredge"
  | "Drogoz"
  | "Evie"
  | "Fernando"
  | "Furia"
  | "Grohk"
  | "Grover"
  | "Imani"
  | "Inara"
  | "Io"
  | "Jenos"
  | "Khan"
  | "Kinessa"
  | "Koga"
  | "Lex"
  | "Lian"
  | "Maeve"
  | "Makoa"
  | "MalDamba"
  | "Moji"
  | "Octavia"
  | "Pip"
  | "Raum"
  | "Rei"
  | "Ruckus"
  | "Saati"
  | "Seris"
  | "ShaLin"
  | "Skye"
  | "Strix"
  | "Talus"
  | "Terminus"
  | "Tiberius"
  | "Torvald"
  | "Tyra"
  | "Vatu"
  | "Viktor"
  | "Vivian"
  | "Vora"
  | "Willo"
  | "Yagorath"
  | "Ying"
  | "Zhin"

export type Ranks = "Qualifying"
  | "Bronze V"
  | "Bronze IV"
  | "Bronze III"
  | "Bronze II"
  | "Bronze I"
  | "Silver V"
  | "Silver IV"
  | "Silver III"
  | "Silver II"
  | "Silver I"
  | "Gold V"
  | "Gold IV"
  | "Gold III"
  | "Gold II"
  | "Gold I"
  | "Platinum V"
  | "Platinum IV"
  | "Platinum II"
  | "Platinum III"
  | "Platinum I"
  | "Diamond V"
  | "Diamond IV"
  | "Diamond III"
  | "Diamond II"
  | "Diamond I"
  | "Master"
  | "Grandmaster"